server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://114.116.246.84:3306/test1?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: '@ZP0211'

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.test.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl